[package]
name = "notus"
version = "0.1.2"
edition = "2021"
license = "GPL-3.0"
description = "A simple terminal notes app"
repository = "https://github.com/jamdotjar/notus"
keywords = ["notes", "markdown"]
categories = ["command-line-utilities", "text-editors"]
exclude = [
    ".vscode/*",
    "Cargo.toml.orig",
    ".github/*"
]


[dependencies]
rand = "0.8.5"
assert_cmd = "2.0.14"
predicates = "3.1.0"
scan_fmt = "0.2.6"
serde = { version = "1.0", features = ["derive"] }
chrono = "0.4.37"
serde_json = '1.0'
bincode = "1.3.3"
crossterm = "0.27.0"
dirs = "5.0.1"
rfd = "0.14.1"
[dependencies.cursive]
version = "0.20.0"
default-features = false
features = ["markdown"]

[features]
default = ["crossterm-backend", "cursive/markdown"]
# ncurses-backend = ["cursive/ncurses-backend"]
pancurses-backend = ["cursive/pancurses-backend"]
termion-backend = ["cursive/termion-backend"]
crossterm-backend = ["cursive/crossterm-backend"]
blt-backend = ["cursive/blt-backend"]
markdown = ["cursive/markdown"]
